export type Mode = 'text' | 'images' | 'documents' | 'excel' | 'folders';
export type Input = { id: string; name: string; path?: string; originalPath?: string; size?: number; types: Mode[]; text?: string };
export type Rule = { value: string; regex: boolean };
export type Options = {
  view: string;
  precision: 'smart' | 'word' | 'character';
  ignoreCase: boolean;
  ignoreWhitespace: boolean;
  ignoreRules: Rule[];
  wrap: boolean;
  hideUnchanged: boolean;
  threshold: number;
  opacity: number;
  flickerMs: number;
  ocr: boolean;
  page: number;
  leftSheet: string;
  rightSheet: string;
  formulas: boolean;
  hideRows: boolean;
  hideColumns: boolean;
  dateOrder: 'none' | 'US' | 'EU';
  sortColumn: string;
  exclusions: string[];
  password?: string;
};
export type CompareTab = {
  id: string;
  title: string;
  type: Mode;
  left: Input | null;
  right: Input | null;
  available: Input[];
  options: Options;
  result: any;
  busy: boolean;
  progress: number;
  phase: string;
  jobId?: string;
  error?: string;
  dirty: boolean;
};
export type Preferences = { restoreTabs: boolean; skippedCommit: string | null; recentProjects: { id: string; name: string; path: string }[]; tabs?: CompareTab[] };
export type CompareEvent = { id: string; kind: 'progress' | 'result' | 'error'; value?: number; phase?: string; result?: any; error?: string };
export type AppApi = {
  minimizeWindow(): Promise<void>; toggleMaximizeWindow(): Promise<boolean>; isWindowMaximized(): Promise<boolean>; closeWindow(): Promise<void>;
  onWindowMaximizedChange(callback: (value: boolean) => void): () => void;
  pathsForFiles(files: FileList | File[]): string[];
  describeInputs(paths: string[]): Promise<Input[]>;
  browseInputs(type: Mode): Promise<Input[]>;
  readText(input: Input): Promise<string>;
  preview(input: Input): Promise<string | null>;
  startCompare(request: { type: Mode; left: Input; right: Input; options: Options }): Promise<string>;
  cancelCompare(id: string): Promise<void>;
  onCompareEvent(callback: (event: CompareEvent) => void): () => void;
  getSettings(): Promise<Preferences>; setSettings(patch: Partial<Preferences>): Promise<Preferences>;
  saveProject(project: { id?: string; name: string; tabs: CompareTab[] }): Promise<{ id: string; path: string }>;
  loadProject(path: string): Promise<{ id: string; name: string; tabs: CompareTab[] }>;
  saveExport(request: { name: string; content: string; base64?: boolean; filters: { name: string; extensions: string[] }[] }): Promise<string | null>;
  exportPdf(request: { title: string; lines: string[] }): Promise<string | null>;
  checkUpdate(): Promise<{ sha: string; installed: string | null } | null>;
  updateNow(): Promise<boolean>; updateAfterClose(): Promise<boolean>;
};
declare global { interface Window { api: AppApi } }
