export type Mode = 'text' | 'images' | 'documents' | 'excel' | 'folders';
export type Input = { id: string; name: string; path?: string; originalPath?: string; size?: number; types: Mode[]; text?: string };
export type Rule = { value: string; regex: boolean };
export type Options = {
  view: string;
  splitOrientation: 'vertical' | 'horizontal';
  precision: 'smart' | 'word' | 'character';
  syntaxHighlight: boolean;
  ignoreCase: boolean;
  ignoreWhitespace: boolean;
  ignoreRules: Rule[];
  wrap: boolean;
  syncScroll: boolean;
  syncLineHeights: boolean;
  hideUnchanged: boolean;
  threshold: number;
  minRegionSize: number;
  regionGap: number;
  autoAlign: boolean;
  offsetX: number;
  offsetY: number;
  scale: number;
  rotation: number;
  perspectiveX: number;
  perspectiveY: number;
  flipX: boolean;
  flipY: boolean;
  opacity: number;
  sliderNoOverlap: boolean;
  flickerMs: number;
  transitionMs: number;
  ocr: boolean;
  page: number;
  rightPageOrder: number[];
  leftSheet: string;
  rightSheet: string;
  formulas: boolean;
  alignRows: boolean;
  alignColumns: boolean;
  hideRows: boolean;
  hideColumns: boolean;
  dateOrder: 'none' | 'US' | 'EU';
  sortColumn: string;
  exclusions: string[];
  compareMetadata: boolean;
  password?: string;
};
export type CompareTab = {
  id: string;
  title: string;
  type: Mode;
  left: Input | null;
  right: Input | null;
  available: Input[];
  options: Options;
  result: any;
  busy: boolean;
  progress: number;
  phase: string;
  jobId?: string;
  needsCompare?: boolean;
  error?: string;
  scans?: { at: string; count: number; changed: number; options: Partial<Options> }[];
  decisions?: Record<number, 'accept' | 'reject'>;
};
export type RecentCompare = { type: Mode; left: string; right: string };
export type Preferences = { restoreTabs: boolean; recentCompareLimit: number; recentCompares: RecentCompare[]; lastImageView?: string; tabs?: CompareTab[]; activeTabId?: string };
export type CompareEvent = { id: string; kind: 'progress' | 'result' | 'error' | 'cancelled'; value?: number; phase?: string; result?: any; error?: string };
export type AppApi = {
  minimizeWindow(): Promise<void>; toggleMaximizeWindow(): Promise<boolean>; isWindowMaximized(): Promise<boolean>; closeWindow(): Promise<void>;
  takeWindowBootstrap(): Promise<{ initialTab: CompareTab | null; primary: boolean }>;
  reportActiveTab(activeTab: { type: Mode; left: boolean; right: boolean } | null): void;
  beginTabDrag(token: string, tab: CompareTab, tabCount: number): string;
  endTabDrag(token: string): Promise<void>;
  acceptTabDrag(token: string): Promise<CompareTab | null>;
  detachTab(token: string, position: { x: number; y: number }): Promise<boolean>;
  onRemoveTransferredTab(callback: (id: string, closeWindow: boolean) => void): () => void;
  onTabDragState(callback: (preview: Pick<CompareTab, 'id' | 'title' | 'type'> | null) => void): () => void;
  onWindowMaximizedChange(callback: (value: boolean) => void): () => void;
  onPrimaryWindowChange(callback: (value: boolean) => void): () => void;
  takeDroppedPaths(): string[];
  describeInputs(paths: string[]): Promise<Input[]>;
  takeStartupOpenRequests(): Promise<{ paths: string[]; reuseExisting: boolean }[]>;
  onOpenPaths(callback: (paths: string[], mode: 'reuse' | 'new') => void): () => void;
  browseInputs(type: Mode): Promise<Input[]>;
  readText(input: Input): Promise<string>;
  preview(input: Input): Promise<string | null>;
  startCompare(request: { id: string; type: Mode; left: Input; right: Input; options: Options }): Promise<string>;
  cancelCompare(id: string): Promise<void>;
  releaseCompareAssets(id: string): Promise<void>;
  onCompareEvent(callback: (event: CompareEvent) => void): () => void;
  getSettings(): Promise<Preferences>; setSettings(patch: Partial<Preferences>): Promise<Preferences>;
  getShellContextMenuInstalled(): Promise<boolean>; setShellContextMenuInstalled(enabled: boolean): Promise<boolean>;
  getAppDataPath(): Promise<string>; openAppDataFolder(): Promise<void>;
  openExternalUrl(url: string): Promise<void>;
  checkForUpdates(): Promise<{ status: 'up-to-date' }>;
  writeClipboardText(text: string): Promise<void>;
  exportImageView(request: { title: string; result: any; options: Options; toClipboard: boolean; flickerRight?: boolean }): Promise<string | null>;
  exportText(request: { title: string; leftText: string; rightText: string; leftName?: string; rightName?: string; kind: 'original' | 'changed' | 'unified'; fenced?: boolean; toClipboard: boolean }): Promise<string | null>;
  exportPdf(request: { title: string; lines?: string[]; layout?: 'side' | 'redline'; leftText?: string; rightText?: string; chunks?: any[]; imageView?: { result: any; options: Options; flickerRight?: boolean } }): Promise<string | null>;
  exportDocx(request: { title: string; chunks: any[]; tracked: boolean }): Promise<string | null>;
  exportXlsx(request: { title: string; rows: Record<string, unknown>[] }): Promise<string | null>;
};
declare global { interface Window { api: AppApi } }
